# Generated by Django 5.2.12 on 2026-03-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_relation', models.CharField(choices=[('father', 'Ayah'), ('mother', 'Ibu'), ('guardian', 'Wali'), ('grandparent', 'Kakek/Nenek'), ('sibling', 'Kakak/Adik'), ('other', 'Lainnya')], default='father', max_length=50, verbose_name='Jenis Hubungan Diminta')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('expired', 'Kedaluwarsa')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Persetujuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Kedaluwarsa')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_link_requests', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to=settings.AUTH_USER_MODEL, verbose_name='Wali Murid/Santri')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_link_requests', to=settings.AUTH_USER_MODEL, verbose_name='Siswa/Santri')),
            ],
            options={
                'verbose_name': 'Permintaan Link',
                'verbose_name_plural': 'Permintaan Link',
                'db_table': 'smart_linking_requests',
                'indexes': [models.Index(fields=['status'], name='smart_linki_status_bc7441_idx'), models.Index(fields=['expires_at'], name='smart_linki_expires_e4a335_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('father', 'Ayah'), ('mother', 'Ibu'), ('guardian', 'Wali'), ('grandparent', 'Kakek/Nenek'), ('sibling', 'Kakak/Adik'), ('other', 'Lainnya')], default='father', max_length=50, verbose_name='Jenis Hubungan')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Hubungan Utama')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Terverifikasi')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL, verbose_name='Wali Murid/Santri')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='Siswa/Santri')),
            ],
            options={
                'verbose_name': 'Link Wali Murid',
                'verbose_name_plural': 'Link Wali Murid',
                'db_table': 'smart_linking_parent_student',
                'indexes': [models.Index(fields=['parent'], name='smart_linki_parent__673285_idx'), models.Index(fields=['student'], name='smart_linki_student_e3569f_idx'), models.Index(fields=['is_verified'], name='smart_linki_is_veri_3c04ae_idx')],
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
