# Generated by Django 5.2.12 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="no_kk",
            field=models.CharField(
                blank=True,
                help_text="Nomor Kartu Keluarga untuk relasi siswa dengan orang tua",
                max_length=20,
                verbose_name="No. KK",
            ),
        ),
    ]
