# Generated by Django 5.2.12 on 2026-03-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('spp', 'SPP Bulanan'), ('registration', 'Registrasi'), ('book', 'Buku'), ('uniform', 'Seragam'), ('activity', ' Kegiatan'), ('other', 'Lainnya')], default='spp', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Menunggu Pembayaran'), ('paid', 'Lunas'), ('overdue', 'Jatuh Tempo'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Bulan (1-12) untuk SPP', null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Tahun untuk SPP', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_invoices', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'finance_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('transfer', 'Transfer Bank'), ('va', 'Virtual Account'), ('credit_card', 'Kartu Kredit'), ('e_wallet', 'E-Wallet'), ('qris', 'QRIS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('success', 'Berhasil'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan')], default='pending', max_length=20)),
                ('gateway', models.CharField(blank=True, choices=[('midtrans', 'Midtrans'), ('xendit', 'Xendit')], max_length=20, null=True)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID dari payment gateway', max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID dari payment gateway', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Response lengkap dari payment gateway', null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'db_table': 'finance_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midtrans_merchant_id', models.CharField(blank=True, max_length=100)),
                ('midtrans_client_key', models.CharField(blank=True, max_length=200)),
                ('midtrans_server_key', models.CharField(blank=True, max_length=200)),
                ('midtrans_is_production', models.BooleanField(default=False)),
                ('midtrans_enabled', models.BooleanField(default=False)),
                ('xendit_api_key', models.CharField(blank=True, max_length=200)),
                ('xendit_is_production', models.BooleanField(default=False)),
                ('xendit_enabled', models.BooleanField(default=False)),
                ('callback_secret', models.CharField(blank=True, help_text='Secret untuk verifikasi callback', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Konfigurasi Payment Gateway',
                'verbose_name_plural': 'Konfigurasi Payment Gateway',
                'db_table': 'finance_payment_config',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='finance_inv_invoice_dd3aad_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_7c9653_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='finance_inv_due_dat_58b34d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student'], name='finance_inv_student_25a218_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['parent'], name='finance_inv_parent__0e8d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='finance_pay_payment_2119dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_632995_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway'], name='finance_pay_gateway_a92dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='finance_pay_invoice_e4df34_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_by'], name='finance_pay_paid_by_7122bc_idx'),
        ),
    ]
