# Generated by Django 5.2.12 on 2026-03-23 07:55

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='Nama lengkap sekolah/pesantren', max_length=255, verbose_name='Nama Instansi')),
                ('kode_instansi', models.CharField(help_text='Kode unik untuk instansii. Contoh: UIM, UNESA, ALFALAH', max_length=20, unique=True, verbose_name='Kode Instansi')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Contoh: uim, unesa, al-falah', unique=True, verbose_name='Slug')),
                ('sub_brand_name', models.CharField(blank=True, help_text='Nama brand alternatif yang ditampilkan di dashboard', max_length=100, verbose_name='Nama Sub-brand')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenants/favicons/', verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code. Contoh: #3B82F6', max_length=7, verbose_name='Warna Primer')),
                ('secondary_color', models.CharField(default='#8B5CF6', help_text='Hex color code. Contoh: #8B5CF6', max_length=7, verbose_name='Warna Sekunder')),
                ('theme_config', models.JSONField(blank=True, default=dict, help_text='Konfigurasi tema tambahan untuk white-labeling', verbose_name='Konfigurasi Tema')),
                ('custom_domain', models.CharField(blank=True, help_text='Domain kustom. Contoh: sakti.uim.ac.id', max_length=255, verbose_name='Custom Domain')),
                ('is_active', models.BooleanField(default=True, help_text='Non-aktifkan untuk menonaktifkan akses', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=50, verbose_name='Paket Langganan')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Dibayar Sampai')),
                ('spp_amount', models.DecimalField(decimal_places=2, default=500000, help_text='Jumlah SPP default per bulan', max_digits=12, verbose_name='Jumlah SPP Bulanan')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Domain Utama')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
