# Generated by Django 5.2.12 on 2026-03-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: 2025/2026', max_length=50, verbose_name='Nama Tahun Ajaran')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
                ('is_current', models.BooleanField(default=False, verbose_name='Tahun Ajaran Sekarang')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Kelas 1, Kelas 2 SMA', max_length=50, verbose_name='Nama Tingkat/Kelas')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Tingkat')),
                ('grade_type', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('smk', 'SMK'), ('pesantren', 'Pesantren')], default='sd', max_length=20, verbose_name='Tipe')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Mapel/Kitab')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('subject_type', models.CharField(choices=[('general', ' Umum'), ('religious', 'Agama'), ('language', 'Bahasa'), ('science', 'Sains'), ('arts', 'Seni'), ('sports', 'Olahraga')], default='general', max_length=20, verbose_name='Tipe')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Kelas 1-A', max_length=50, verbose_name='Nama Kelas')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Kapasitas')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor Ruang')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academic.academicyear', verbose_name='Tahun Ajaran')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Wali Kelas/Ustadz')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academic.grade', verbose_name='Tingkat')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['grade__level', 'name'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('graduated', 'Lulus'), ('transferred', 'Pindah'), ('suspended', 'Skorsing'), ('dropout', 'Dropout')], default='active', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.classroom', verbose_name='Kelas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Siswa/Santri')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homeroom', models.BooleanField(default=False, verbose_name='Wali Kelas')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.academicyear', verbose_name='Tahun Ajaran')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.classroom', verbose_name='Kelas')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.subject', verbose_name='Mapel/Kitab')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Guru/Ustadz')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'unique_together': {('teacher', 'subject', 'classroom', 'academic_year')},
            },
        ),
    ]
