# Generated by Django 5.2.12 on 2026-03-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode')),
                ('resource', models.CharField(choices=[('tenant', 'Tenant'), ('user', 'User'), ('academic_year', 'Tahun Ajaran'), ('subject', 'Mata Pelajaran'), ('grade', 'Tingkat'), ('classroom', 'Kelas'), ('enrollment', 'Pendaftaran'), ('attendance', 'Absensi'), ('score', 'Nilai'), ('finance', 'Keuangan'), ('report', 'Laporan')], max_length=30, verbose_name='Resource')),
                ('action', models.CharField(choices=[('create', 'Buat'), ('read', 'Baca'), ('update', 'Ubah'), ('delete', 'Hapus'), ('approve', 'Approve'), ('export', 'Export')], max_length=20, verbose_name='Aksi')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='Peran')),
                ('is_granted', models.BooleanField(default=True, verbose_name='Diberikan')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
