# Generated by Django 5.2.12 on 2026-03-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('daily', 'Harian'), ('session', 'Per Jam Pelajaran'), ('activity', 'Ekstrakurikuler/Diniyah')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Hadir'), ('absent', 'Tidak Hadir'), ('late', 'Terlambat'), ('excused', 'Izin'), ('sick', 'Sakit')], default='present', max_length=20)),
                ('date', models.DateField()),
                ('session', models.PositiveSmallIntegerField(blank=True, help_text='Nomor sesi untuk attendance_type=session', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academic.classroom')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academic.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'db_table': 'activities_attendance',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('daily', 'Tugas Harian'), ('midterm', 'UTS'), ('final', 'UAS'), ('task', 'Tugas'), ('project', 'Proyek'), ('practice', 'Praktik')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('title', models.CharField(help_text='Judul tugas/ujian', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester (1 atau 2)')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academic.academicyear')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='academic.classroom')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academic.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
                'db_table': 'activities_scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('attendance', 'Absensi'), ('score', 'Nilai Baru'), ('activity', 'Foto Kegiatan'), ('announcement', 'Pengumuman'), ('assignment', 'Tugas Baru')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/')),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='activities.attendance')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='academic.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='activities.score')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
                'db_table': 'activities_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_notifications', to=settings.AUTH_USER_MODEL)),
                ('timeline_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.timelineevent')),
            ],
            options={
                'verbose_name': 'Notifikasi Timeline',
                'verbose_name_plural': 'Notifikasi Timeline',
                'db_table': 'activities_timeline_notifications',
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='activities__date_8211a9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='activities__student_c3a339_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='activities__status_71ad06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['recorded_by'], name='activities__recorde_03e368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'attendance_type', 'session', 'subject')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student', 'subject'], name='activities__student_43b789_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['score_type'], name='activities__score_t_ee2380_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['semester'], name='activities__semeste_21fc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['recorded_by'], name='activities__recorde_aeda9f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['event_type'], name='activities__event_t_1eef48_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['published'], name='activities__publish_9f5120_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['created_at'], name='activities__created_8ab88a_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinenotification',
            index=models.Index(fields=['parent', 'is_read'], name='activities__parent__5e6236_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timelinenotification',
            unique_together={('timeline_event', 'parent')},
        ),
    ]
